apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnginx-deployment
  labels:
    app: gnginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gnginx
  template:
    metadata:
      labels:
        app: gnginx
    spec:
      containers:
      - name: gnginx
        image: justalittlenoob/graphene-sgx-nginx:0.3
        ports:
        - containerPort: 8002
        command: ['sh', '-c', '/home/gnginx_run.sh && sleep 3600']
        volumeMounts:
        - name: dev-isgx
          mountPath: /dev/isgx
        - name: dev-gsgx
          mountPath: /dev/gsgx
        securityContext:
          privileged: true
      volumes:
      - name: dev-isgx
        hostPath:
          path: /dev/isgx
          type: CharDevice
      - name: dev-gsgx
        hostPath:
          path: /dev/gsgx
          type: CharDevice
