apiVersion: apps/v1
kind: Deployment
metadata:
  name: zwolfssl-deployment
  labels:
    app: zwolfssl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zwolfssl
  template:
    metadata:
      labels:
        app: zwolfssl
    spec:
      containers:
      - name: zwolfssl-s
        image: justalittlenoob/slimwolf:0.2
        ports:
        - containerPort: 11111
        command: ['sh', '-c', '/home/runsgx_s.sh && sleep 3600']
        volumeMounts:
        - name: dev-sgx
          mountPath: /dev/isgx
        securityContext:
          privileged: true
      - name: zwolfssl-c
        image: justalittlenoob/slimwolf:0.2
        ports:
        - containerPort: 11111
        command: ['sh', '-c', 'sleep 10 && /home/runsgx_c.sh && sleep 3600']
        volumeMounts:
        - name: dev-sgx
          mountPath: /dev/isgx
        securityContext:
          privileged: true
      volumes:
      - name: dev-sgx
        hostPath:
          path: /dev/isgx
          type: CharDevice